import { Card } from 'antd';
import { TreeChart, TreeTableChart } from '@/common/components/index';
import styles from './index.less';

export default function IndexPage(props) {
  const relation = [
    {
      level: 0,
      id: 'click_num',
      parentId: 0,
      childrenLength: 2,
      count: '乘',
      label: '点击量',
      index: 0,
    },
    {
      level: 1,
      id: 'arrival_num',
      parentId: 'click_num',
      childrenLength: 2,
      count: '除',
      label: '到达达量',
      index: 0,
    },
    {
      level: 2,
      id: 10,
      parentId: 'arrival_num',
      childrenLength: 2,
      count: '乘',
      label: '到达达量',
      index: 0,
    },
    {
      level: 2,
      id: 9,
      parentId: 'arrival_num',
      childrenLength: 4,
      count: '',
      label: '到达达量',
      index: 1,
    },
    {
      level: 1,
      id: 'click_rate',
      parentId: 'click_num',
      childrenLength: 2,
      count: '乘',
      label: '点击率',
      index: 1,
    },
    {
      level: 3,
      id: 4,
      parentId: 9,
      childrenLength: 0,
      count: '正',
      label: '发送成功量',
      index: 0,
    },
    {
      level: 3,
      id: 5,
      parentId: 9,
      childrenLength: 0,
      count: '正',
      label: '发送成功量',
      index: 1,
    },
    {
      level: 3,
      id: 6,
      parentId: 9,
      childrenLength: 0,
      count: '负',
      label: '功推送量',
      index: 2,
    },
    {
      level: 3,
      id: 7,
      parentId: 9,
      childrenLength: 0,
      count: '负',
      label: '成送量',
      index: 3,
    },
    {
      level: 2,
      id: 8,
      parentId: 'click_rate',
      childrenLength: 4,
      count: '',
      label: '到达率',
      index: 0,
    },
    {
      level: 2,
      id: 31,
      parentId: 'click_rate',
      childrenLength: 0,
      count: '',
      label: '发送成功量',
      index: 1,
    },
    {
      level: 3,
      id: 34,
      parentId: 8,
      childrenLength: 0,
      count: '正',
      label: '发送成功量',
      index: 0,
    },
    {
      level: 3,
      id: 35,
      parentId: 8,
      childrenLength: 0,
      count: '负',
      label: '发送成功量',
      index: 1,
    },
    {
      level: 3,
      id: 36,
      parentId: 8,
      childrenLength: 0,
      count: '负',
      label: '功推送量',
      index: 2,
    },
    {
      level: 3,
      id: 37,
      parentId: 8,
      childrenLength: 0,
      count: '负',
      label: '成送量',
      index: 3,
    },
    {
      level: 3,
      id: 11,
      parentId: 10,
      childrenLength: 2,
      count: '乘',
      label: '点击率',
      index: 0,
    },
    {
      level: 3,
      id: 12,
      parentId: 10,
      childrenLength: 3,
      count: '',
      label: '点击率',
      index: 1,
    },
    {
      level: 4,
      id: 13,
      parentId: 11,
      childrenLength: 2,
      count: '乘',
      label: '点击率',
      index: 0,
    },
    {
      level: 4,
      id: 14,
      parentId: 11,
      childrenLength: 0,
      count: '除',
      label: '点击率',
      index: 1,
    },
    {
      level: 4,
      id: 15,
      parentId: 12,
      childrenLength: 0,
      count: '负',
      label: '点击率',
      index: 0,
    },
    {
      level: 4,
      id: 16,
      parentId: 12,
      childrenLength: 0,
      count: '正',
      label: '点击率',
      index: 1,
    },
    {
      level: 4,
      id: 17,
      parentId: 12,
      childrenLength: 0,
      count: '负',
      label: '点击率',
      index: 2,
    },
    {
      level: 5,
      id: 18,
      parentId: 13,
      childrenLength: 2,
      count: '乘',
      label: '点击率',
      index: 0,
    },
    {
      level: 5,
      id: 19,
      parentId: 13,
      childrenLength: 0,
      count: '除',
      label: '点击率',
      index: 1,
    },
    {
      level: 6,
      id: 20,
      parentId: 18,
      childrenLength: 0,
      count: '乘',
      label: '点击率',
      index: 0,
    },
    {
      level: 6,
      id: 21,
      parentId: 18,
      childrenLength: 0,
      count: '除',
      label: '点击率',
      index: 1,
    },
  ];
  const overview = [
    {
      key: 'click_num',
      id: 'click_num',
      label: '点击量', // 指标
      explain: 'New York No. 1 Lake Park',
      parentId: 0,
      level: 0,
      index: 0,
      count: '乘',
      childrenLength: 2,
      children: [
        {
          key: 'arrival_num',
          id: 'arrival_num',
          parentId: 'click_num',
          level: 1,
          index: 0,
          count: '除',
          childrenLength: 2,
          label: '到达达量',
          explain: 'London No. 1 Lake Park',
          children: [
            {
              key: 132,
              id: 132,
              parentId: 'arrival_num',
              level: 2,
              index: 0,
              childrenLength: 2,
              label: '到达率',
              count: '除',
              explain: 'London No. 2 Lake Park',
              children: [
                {
                  key: 1321,
                  id: 1321,
                  parentId: 132,
                  level: 3,
                  index: 0,
                  count: '乘',
                  childrenLength: 2,
                  label: '发送成功用户数',
                  explain: 'London No. 3 Lake Park',
                  children: [
                    {
                      key: 13212,
                      id: 13212,
                      level: 4,
                      index: 0,
                      childrenLength: 0,
                      parentId: 1321,
                      count: '',
                      label: '人均成功推动量',
                      explain: 'London No. 4 Lake Park',
                    },
                    {
                      key: 13211,
                      id: 13211,
                      parentId: 1321,
                      level: 4,
                      index: 1,
                      count: '',
                      childrenLength: 1,
                      label: '发送成功用户数',
                      explain: 'London No. 3 Lake Park',
                      children: [
                        {
                          key: 132111,
                          id: 132111,
                          parentId: 13211,
                          level: 5,
                          index: 0,
                          count: '负',
                          childrenLength: 0,
                          label: '活跃用户数',
                          explain: 'London No. 3 Lake Park',
                        },
                      ],
                    },
                  ],
                },
                {
                  key: 1322,
                  id: 1322,
                  level: 3,
                  index: 1,
                  count: '乘',
                  childrenLength: 2,
                  parentId: 132,
                  label: '人均成功推动量',
                  explain: 'London No. 4 Lake Park',
                  children: [
                    {
                      key: 13222,
                      id: 13222,
                      parentId: 1322,
                      level: 4,
                      index: 0,
                      count: '',
                      childrenLength: 1,
                      label: '发送成功用户数',
                      explain: 'London No. 3 Lake Park',
                      children: [
                        {
                          key: 132222,
                          id: 132222,
                          parentId: 13222,
                          level: 5,
                          index: 0,
                          count: '正',
                          childrenLength: 0,
                          label: '活跃用户数',
                          explain: 'London No. 3 Lake Park',
                        },
                      ],
                    },
                    {
                      key: 13221,
                      id: 13221,
                      level: 4,
                      index: 1,
                      childrenLength: 2,
                      parentId: 1322,
                      count: '除',
                      label: '人均成功推动量',
                      explain: 'London No. 4 Lake Park',
                      children: [
                        {
                          key: 132211,
                          id: 132211,
                          level: 5,
                          index: 0,
                          childrenLength: 0,
                          parentId: 13221,
                          count: '',
                          label: '人均成功推动量',
                          explain: 'London No. 4 Lake Park',
                        },
                        {
                          key: 132212,
                          id: 132212,
                          parentId: 13221,
                          level: 5,
                          index: 1,
                          count: '',
                          childrenLength: 1,
                          label: '发送成功用户数',
                          explain: 'London No. 3 Lake Park',
                          children: [
                            {
                              key: 1322122,
                              id: 1322122,
                              parentId: 132212,
                              level: 6,
                              index: 0,
                              count: '负',
                              childrenLength: 0,
                              label: '活跃用户数',
                              explain: 'London No. 3 Lake Park',
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              key: 131,
              id: 131,
              parentId: 'arrival_num',
              level: 2,
              index: 1,
              childrenLength: 2,
              label: '发送成功量',
              count: '乘',
              explain: 'London No. 2 Lake Park',
              children: [
                {
                  key: 1311,
                  id: 1311,
                  parentId: 131,
                  level: 3,
                  index: 0,
                  count: '除',
                  childrenLength: 2,
                  label: '发送成功用户数',
                  explain: 'London No. 3 Lake Park',
                  children: [
                    {
                      key: 13111,
                      id: 13111,
                      parentId: 1311,
                      level: 4,
                      index: 0,
                      count: '',
                      childrenLength: 1,
                      label: '发送成功用户数',
                      explain: 'London No. 3 Lake Park',
                      children: [
                        {
                          key: 131111,
                          id: 131111,
                          parentId: 13111,
                          level: 5,
                          index: 0,
                          count: '正',
                          childrenLength: 0,
                          label: '活跃用户数',
                          explain: 'London No. 3 Lake Park',
                        },
                      ],
                    },
                    {
                      key: 13122,
                      id: 13122,
                      level: 4,
                      index: 1,
                      childrenLength: 0,
                      parentId: 1311,
                      count: '',
                      label: '人均成功推动量',
                      explain: 'London No. 4 Lake Park',
                    },
                  ],
                },
                {
                  key: 1312,
                  id: 1312,
                  level: 3,
                  index: 1,
                  count: '',
                  childrenLength: 0,
                  parentId: 131,
                  label: '人均成功推动量',
                  explain: 'London No. 4 Lake Park',
                },
              ],
            },
          ],
        },
        {
          key: 'click_rate',
          id: 'click_rate',
          parentId: 'click_num',
          level: 1,
          index: 1,
          childrenLength: 2,
          count: '乘',
          label: '点击率',
          explain: 'New York No. 2 Lake Park',
          children: [
            {
              key: 111,
              id: 111,
              parentId: 'click_rate',
              level: 2,
              index: 0,
              childrenLength: 2,
              label: '发送成功量',
              count: '乘',
              explain: 'London No. 2 Lake Park',
              children: [
                {
                  key: 1111,
                  id: 1111,
                  parentId: 111,
                  level: 3,
                  index: 0,
                  count: '除',
                  childrenLength: 2,
                  label: '发送成功用户数',
                  explain: 'London No. 3 Lake Park',
                  children: [
                    {
                      key: 11111,
                      id: 11111,
                      parentId: 1111,
                      level: 4,
                      index: 0,
                      count: '',
                      childrenLength: 1,
                      label: '发送成功用户数',
                      explain: 'London No. 3 Lake Park',
                      children: [
                        {
                          key: 111111,
                          id: 111111,
                          parentId: 11111,
                          level: 5,
                          index: 0,
                          count: '正',
                          childrenLength: 0,
                          label: '活跃用户数',
                          explain: 'London No. 3 Lake Park',
                        },
                      ],
                    },
                    {
                      key: 11122,
                      id: 11122,
                      level: 4,
                      index: 1,
                      childrenLength: 0,
                      parentId: 1111,
                      count: '',
                      label: '人均成功推动量',
                      explain: 'London No. 4 Lake Park',
                    },
                  ],
                },
                {
                  key: 1112,
                  id: 1112,
                  level: 3,
                  index: 1,
                  count: '',
                  childrenLength: 0,
                  parentId: 131,
                  label: '人均成功推动量',
                  explain: 'London No. 4 Lake Park',
                },
              ],
            },
            {
              key: 112,
              id: 112,
              parentId: 'arrival_num',
              level: 2,
              index: 1,
              childrenLength: 0,
              label: '到达率',
              count: '',
              explain: 'London No. 2 Lake Park',
            },
          ],
        },
      ],
    },
  ];
  // 点击图表跳转
  const treeChartClick = (item) => {
    const { id } = item;
    const dom = document.getElementById(`detail${id}`);
    if (dom) {
      dom.scrollIntoView(false);
    }
  };

  return (
    <div>
      <h1 className={`${styles.title} text-4xl`}>树形图表</h1>
      <h3>关系图</h3>
      <Card bordered={false}>
        <TreeChart data={relation} doLabelClick={treeChartClick} />
      </Card>
      <h3>概况表格</h3>
      <Card bordered={false}>
        <TreeTableChart
          data={overview}
          doLabelClick={treeChartClick}
        />
      </Card>
    </div>
  );
}
